language: scala
jdk:
  - oraclejdk8
scala:
  - "2.11.7"
before_install:
  - mkdir /tmp/dynamodb
  - wget -O - http://dynamodb-local.s3-website-us-west-2.amazonaws.com/dynamodb_local_latest.tar.gz | tar xzC /tmp/dynamodb
  - java -Djava.library.path=/tmp/dynamodb/DynamoDBLocal_lib -Xss1m -Xms256m -Xmx256m -jar /tmp/dynamodb/DynamoDBLocal.jar -inMemory &
